# Generated by Django 5.2.9 on 2026-03-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('strike', models.FloatField()),
                ('ltp', models.FloatField(blank=True, null=True)),
                ('call_oi', models.FloatField(blank=True, null=True)),
                ('put_oi', models.FloatField(blank=True, null=True)),
                ('iv', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('theta', models.FloatField(blank=True, null=True)),
                ('gamma', models.FloatField(blank=True, null=True)),
                ('vega', models.FloatField(blank=True, null=True)),
                ('expiry', models.CharField(blank=True, max_length=30, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
